/-
Copyright (c) 2026 Raphael Coelho. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Raphael Coelho
-/
module

public import MathFin.Foundations.ItoIntegralProcessContinuousModification

/-!
# The general-integrand Itô integral as a continuous local martingale

The continuous modification (`itoContinuousMod`) is a martingale that is
continuous only *almost surely* — its `limUnder` paths are junk off the
convergence set. Degenne's `Martingale.IsLocalMartingale` needs paths càdlàg for
**every** `ω`, which forces an everywhere-continuous representative; but the
modification on a null set can only be repaired while staying adapted if the
filtration carries the null sets. This file builds the **null-augmented
filtration** `𝓕 ⊔ 𝓝` (`𝓝` = the σ-algebra of `μ`-null measurable sets) and the
cond-expectation-invariance under it, the measure-theoretic core of the "usual
conditions" upgrade.

## Status

This module is under construction. The committed piece is the measure-theoretic
crux: every `𝓕 ⊔ 𝓝`-measurable set is `μ`-a.e. equal to a `𝓕`-measurable set,
hence conditioning on `𝓕 ⊔ 𝓝` agrees a.e. with conditioning on `𝓕`. The
everywhere-continuous redefinition, the martingale transfer, and the
`IsLocalMartingale` assembly build on top of it.
-/

@[expose] public section

open MeasureTheory ProbabilityTheory Filter Topology
open scoped NNReal ENNReal

namespace MathFin
namespace ItoLocalMartingale

variable {Ω : Type*} {m0 : MeasurableSpace Ω} {μ : Measure Ω}

/-- The σ-algebra generated by the `μ`-null **measurable** sets (so it stays
`≤ m0`). It contains every measurable null set; augmenting a filtration by it
realises the "usual conditions" needed to repair an a.e.-continuous modification
into an everywhere-continuous adapted process. -/
@[reducible] def nullsAlg (m0 : MeasurableSpace Ω) (μ : Measure Ω) : MeasurableSpace Ω :=
  MeasurableSpace.generateFrom {s | MeasurableSet[m0] s ∧ μ s = 0}

lemma nullsAlg_le : nullsAlg m0 μ ≤ m0 :=
  MeasurableSpace.generateFrom_le fun _ hs => hs.1

/-- **The measure-theoretic crux.** Every set measurable for the null-augmented
σ-algebra `m₁ ⊔ 𝓝` is `μ`-a.e. equal to an `m₁`-measurable set. Proof: the
collection of sets that are `=ᵐ` an `m₁`-set is itself a σ-algebra (closed under
complement and countable union for `=ᵐ`) containing both `m₁` (reflexivity) and
the generators of `𝓝` (a null set is `=ᵐ ∅`); being an upper bound of both, it
contains their supremum. -/
theorem exists_ae_eq_of_sup_nulls {m₁ : MeasurableSpace Ω}
    {s : Set Ω} (hs : MeasurableSet[m₁ ⊔ nullsAlg m0 μ] s) :
    ∃ t, MeasurableSet[m₁] t ∧ s =ᵐ[μ] t := by
  -- the collection, packaged as a `MeasurableSpace`
  let M : MeasurableSpace Ω :=
  { MeasurableSet' := fun s => ∃ t, MeasurableSet[m₁] t ∧ s =ᵐ[μ] t
    measurableSet_empty := ⟨∅, m₁.measurableSet_empty, ae_eq_refl _⟩
    measurableSet_compl := fun s ⟨t, ht, hst⟩ =>
      ⟨tᶜ, ht.compl, (ae_eq_set_compl_compl (μ := μ)).mpr hst⟩
    measurableSet_iUnion := fun f hf => by
      choose t ht hft using hf
      refine ⟨⋃ n, t n, MeasurableSet.iUnion ht, ?_⟩
      simpa only [Set.biUnion_univ] using
        ae_eq_set_biUnion (μ := μ) Set.countable_univ (fun n (_ : n ∈ Set.univ) => hft n) }
  have hm₁M : m₁ ≤ M := fun s hs => ⟨s, hs, ae_eq_refl _⟩
  have hnM : nullsAlg m0 μ ≤ M := by
    refine MeasurableSpace.generateFrom_le fun u hu => ⟨∅, m₁.measurableSet_empty, ?_⟩
    rw [ae_eq_set]
    exact ⟨by simpa using hu.2, by simp⟩
  exact (sup_le hm₁M hnM) s hs

/-- **Cond-expectation invariance under the null augmentation.** Conditioning on
the null-augmented σ-algebra `m₁ ⊔ 𝓝` agrees `μ`-a.e. with conditioning on `m₁`:
the extra information is only null sets, which carry no information. Proof:
`μ[f | m₁]` is `m₁`-measurable (hence `(m₁ ⊔ 𝓝)`-measurable) and satisfies the
`(m₁ ⊔ 𝓝)`-set-integral characterisation of the conditional expectation, because
every `(m₁ ⊔ 𝓝)`-set is `=ᵐ` an `m₁`-set (`exists_ae_eq_of_sup_nulls`) over which
the `m₁`-characterisation already holds. -/
theorem condExp_sup_nulls [IsFiniteMeasure μ] {m₁ : MeasurableSpace Ω} (hm₁ : m₁ ≤ m0)
    {f : Ω → ℝ} (hf : Integrable f μ) :
    μ[f | m₁ ⊔ nullsAlg m0 μ] =ᵐ[μ] μ[f | m₁] := by
  have hm : m₁ ⊔ nullsAlg m0 μ ≤ m0 := sup_le hm₁ nullsAlg_le
  haveI : SigmaFinite (μ.trim hm₁) := (isFiniteMeasure_trim hm₁).toSigmaFinite
  haveI : SigmaFinite (μ.trim hm) := (isFiniteMeasure_trim hm).toSigmaFinite
  refine (ae_eq_condExp_of_forall_setIntegral_eq hm hf
    (fun s _ _ => integrable_condExp.integrableOn) (fun s hs _ => ?_)
    ((stronglyMeasurable_condExp.mono le_sup_left).aestronglyMeasurable)).symm
  obtain ⟨t, htm, hst⟩ := exists_ae_eq_of_sup_nulls hs
  rw [setIntegral_congr_set hst, setIntegral_condExp hm₁ hf htm]
  exact (setIntegral_congr_set hst).symm

end ItoLocalMartingale
end MathFin
