/-
Copyright (c) 2026 Raphael Coelho. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Raphael Coelho
-/
module

public import Mathlib
public import MathFin.Foundations.PoissonRandomMeasure

/-!
# The compensated-Poisson isometry kernel (increment-independence cornerstone)

The jump analogue of `Foundations/ItoIsometryAdapted.lean`. For a Poisson random measure `N`,
a past-adapted integrand `φ` is independent of a future compensated space-time increment
`Ñ((s,t] × A)` — here that independence is a *structure field*
(`joint_past_future_independent`), not something re-derived from a weak-Markov property.
From it we get the two energy identities the Itô–Lévy isometry sums:

* diagonal `𝔼[φ² · Ñ(box)²] = 𝔼[φ²] · ν̂(box)` (via `compensated_integral_sq`);
* cross `𝔼[φ · Ñ(box₁) · ψ · Ñ(box₂)] = 0` for disjoint future boxes.

## Provenance

Design mirrors our continuous `ItoIsometryAdapted`; the PRM object is from
`Foundations/PoissonRandomMeasure` (field shape consulted from `cgarryZA/LevyStochCalc`, cited).
The isometry content is our own — LevyStochCalc states it as cited axiom #6.
-/

@[expose] public section

namespace MathFin

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

variable {Ω : Type*} [MeasurableSpace Ω] {E : Type*} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]

/-- The **PRM past `σ`-algebra at time `s`** — generated by the counts on space-time sets
contained in `(-∞, s] × E`. Matches the first σ-algebra in `joint_past_future_independent`. -/
@[reducible] def PoissonRandomMeasure.pastSigma (N : PoissonRandomMeasure P ν) (s : ℝ) :
    MeasurableSpace Ω :=
  ⨆ C ∈ {C : Set (ℝ × E) | C ⊆ Set.Iic s ×ˢ Set.univ ∧ MeasurableSet C},
    MeasurableSpace.comap (fun ω => N.N ω C) inferInstance

/-- `φ` is **adapted at `s`** if it is measurable for the PRM past `σ`-algebra at `s`. -/
def PoissonRandomMeasure.AdaptedAt (N : PoissonRandomMeasure P ν) (s : ℝ) (φ : Ω → ℝ) : Prop :=
  Measurable[N.pastSigma s] φ

/-- **Past-adapted `⟂` future compensated increment.** An integrand adapted at `s` is
independent of `Ñ((s,t] × A)`. The deep content is packaged in the structure field
`joint_past_future_independent`; here we only transport it through `comap`-monotonicity
(`indep_of_indep_of_le_left`) and the measurable map `x ↦ x.toReal − ν̂(box)`. -/
theorem adapted_indepFun_compensated (N : PoissonRandomMeasure P ν) {s t : ℝ}
    (hs : 0 ≤ s) (hst : s < t) {A : Set E} (hA : MeasurableSet A) (hAfin : ν A ≠ ⊤)
    {φ : Ω → ℝ} (hφ : N.AdaptedAt s φ) :
    IndepFun φ (N.compensated (Set.Ioc s t ×ˢ A)) P := by
  have hfield : Indep (N.pastSigma s)
      (MeasurableSpace.comap (fun ω => N.N ω (Set.Ioc s t ×ˢ A)) inferInstance) P :=
    N.joint_past_future_independent hs hst hA hAfin
  have hφ_le : MeasurableSpace.comap φ inferInstance ≤ N.pastSigma s :=
    measurable_iff_comap_le.mp hφ
  have hraw : IndepFun φ (fun ω => N.N ω (Set.Ioc s t ×ˢ A)) P :=
    (IndepFun_iff_Indep _ _ _).mpr (indep_of_indep_of_le_left hfield hφ_le)
  have hcomp := hraw.comp (φ := (id : ℝ → ℝ))
    (ψ := fun x : ℝ≥0∞ => x.toReal - (referenceIntensity ν (Set.Ioc s t ×ˢ A)).toReal)
    measurable_id (by fun_prop)
  simp only [Function.comp_def, id_eq] at hcomp
  exact hcomp

end MathFin
